###
POST https://localhost:5001/api/inicializar-dados/create
Content-Type: application/json

{"Inicio": [
    {

        "Categoria" : "Alimentação",
        "IdProduto" : "1",
        "Nome" : "Arroz",
        "Preco" : 6.7,
        "Quantidade" : 2,
        "CarrinhoId" : "1"
    },
    {

        "Categoria" : "Higiene",
        "IdProduto" : "2",
        "Nome" : "lenço umidecido",
        "Preco" : 3.5,
        "Quantidade" : 4,
        "CarrinhoId" : "1"
    },
    {

        "Categoria" : "Hortifrutti",
        "IdProduto" : "3",
        "Nome" : "banana",
        "Preco" : 1.9,
        "Quantidade" : 1,
        "CarrinhoId" : "1"
    },
    {

        "Categoria" : "Automovel",
        "IdProduto" : "4",
        "Nome" : "farol",
        "Preco" : 36.9,
        "Quantidade" : 2,
        "CarrinhoId" : "1"
    },
    {

        "Categoria" : "eletrodomestico",
        "IdProduto" : "5",
        "Nome" : "aspirador de pó",
        "Preco" : 235.9,
        "Quantidade" : 1,
        "CarrinhoId" : "1"
    }
]}